name: likhaui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  barcode_widget: ^2.0.4
  flutter_svg: ^1.0.3
  signature: ^4.0.0
  order_tracker: ^0.0.2
  order_tracker_zen: ^1.0.0+4
  curved_navigation_bar: ^1.0.1
  convex_bottom_bar: ^3.0.0
  fl_chart: ^0.68.0
  mobile_scanner: ^2.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
